"""add forecast price

Revision ID: 7f2124c8bac6
Revises: 0001_create_market_data
Create Date: 2026-09-09 18:31:31.756176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7f2124c8bac6'
down_revision: Union[str, Sequence[str], None] = '0001_create_market_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('forecast_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'forecast_price')
    # ### end Alembic commands ###
